def apply_market_context_to_image_prompt(base_prompt: str, market_context: dict | None = None) -> str:
    if not market_context:
        return base_prompt

    currency = market_context.get("currency", "")
    country = market_context.get("country", "")

    extra = (
        "\n\nOPTIONAL MARKET HINTS (DO NOT INFER NEW FACTS):\n"
        f"- Preferred currency detection target: {currency}\n"
        f"- Plate priority: prefer extraction patterns common in {country}\n"
        "- Use these hints only for OCR mapping priority, not for guessing hidden values.\n"
    )
    return f"{base_prompt}{extra}"


def build_image_prompt(images, country_rules=None):
    if country_rules is None:
        country_rules = {}

    extra = (
        "\n\nCountry rules:\n"
        f"{country_rules}\n"
        "\nADDITIONAL COUNTRY-AWARE RULES:\n"
        "\n1. License plates:\n"
        "   Prioritize formats from country_rules[\"plate_formats\"]\n"
        "\n2. Inspection:\n"
        "   Detect inspection types from country_rules[\"inspection_types\"]\n"
        "\n3. Currency:\n"
        "   Prefer symbols from country_rules[\"currency_symbols\"]\n"
        "\n4. Text detection:\n"
        "   Use keywords from country_rules[\"language_keywords\"]\n"
        "\nIMPORTANT:\n"
        "If no matches found → fallback to default logic\n"
            "\nVEHICLE VISUAL IDENTIFICATION:\n"
            "You must identify vehicle make and model using visible visual features.\n"
            "\nPrimary sources (in order):\n"
            "1. Front grille logo (badge)\n"
            "2. Steering wheel logo\n"
            "3. Rear badge\n"
            "4. Body shape and design\n"
            "5. Headlights and grille style\n"
            "\nRules:\n"
            "\nPRIORITY RULE:\n"
            "If steering wheel logo is visible, this is the MOST RELIABLE source of brand identification.\n"
            "Use steering wheel logo as primary source over front grille, rear badge, and text.\n"
            "- If logo is visible, treat it as primary source.\n"
            "- If logo is not visible, use best design-based identification.\n"
            "- If uncertain, still return best visible-feature-based guess (no random guess).\n"
            "- Always base guess on visible elements only.\n"
            "\nDetection hints:\n"
            "- circular badge often indicates Volkswagen\n"
            "- V-shaped badge often indicates Nissan\n"
            "- oval badge often indicates Toyota\n"
            "- stylized H often indicates Honda\n"
            "- KIA text logo indicates Kia\n"
            "- steering wheel logo is highly reliable\n"
            "- steering wheel logo should override all other guesses\n"
            "\nVEHICLE TRIM AND EQUIPMENT DETECTION:\n"
            "Estimate equipment level based on clearly visible interior/features only.\n"
            "Look for:\n"
            "- screen size (small / large infotainment)\n"
            "- climate control type (manual knobs vs digital)\n"
            "- steering wheel buttons\n"
            "- seat material (fabric / leather)\n"
            "- parking sensors / camera visibility\n"
            "- dashboard design (basic vs premium)\n"
            "\nTrim rules:\n"
            "- Use only visible evidence.\n"
            "- Do NOT guess premium trim without clear indicators.\n"
            "- If evidence is weak, keep trim_level as basic or medium.\n"
            "\nINTERIOR CONDITION ANALYSIS (CRITICAL):\n"
            "Evaluate interior wear like a professional mechanic/dealer.\n"
            "You must evaluate based on visible wear patterns:\n"
            "1. Steering wheel wear:\n"
            "   - smooth/shiny surface = high wear\n"
            "   - textured surface = lower wear\n"
            "2. Seat condition:\n"
            "   - sagging/wrinkles = high wear\n"
            "   - firm/clean shape = lower wear\n"
            "3. Pedals:\n"
            "   - worn pedal rubber = high usage\n"
            "4. Buttons:\n"
            "   - faded icons = heavy usage\n"
            "5. Overall cleanliness:\n"
            "   - clean interior does NOT mean low mileage\n"
            "   - wear indicators are more important than dirt\n"
            "\nMILEAGE CONSISTENCY CHECK:\n"
            "Compare interior wear with claimed mileage.\n"
            "- low mileage + high wear => possible odometer rollback\n"
            "- high mileage + low wear => suspicious\n"
            "Return mileage_consistency as: consistent / suspicious / unknown\n"
            "\nOUTPUT ADD (top-level JSON fields):\n"
            "\"visual_make\": \"\",\n"
            "\"visual_model\": \"\",\n"
            "\"visual_confidence\": 0.0,\n"
            "\"trim_level\": \"basic|medium|high\",\n"
            "\"features_detected\": [],\n"
            "\"interior_wear_level\": \"low|medium|high\",\n"
            "\"interior_confidence\": 0.0,\n"
            "\"interior_notes\": [],\n"
            "\"mileage_consistency\": \"consistent|suspicious|unknown\"\n"
    )
    return extra

