[phases.setup]
aptPkgs = [
  "libgl1",
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender1",
  "libgl1-mesa-dri"
]

[variables]
PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK = "True"
